language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PACKAGE="asn1-combinators"
  matrix:
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
notifications:
  email: false
